export const GET_POST_LIST_REQUEST = "GET_POST_LIST_REQUEST";
export const POST_POST_LIST_REQUEST = "POST_POST_LIST_REQUEST";
export const GET_POST_ID_REQUEST = "GET_POST_ID_REQUEST";
export const GET_POST_LIST_2_REQUEST = "GET_POST_LIST_2_REQUEST";
